server:
  port: 9000
spring:
  config:
    import: file:etc/app.properties
  datasource:
    url: jdbc:mysql://app-soft-mysql:3306/mzzb_server
    username: mzzb_server
    password: mzzb_server
  rabbitmq:
    host: app-soft-rabbitmq
    port: 5672
    username: admin
    password: admin
  jpa:
    open-in-view: true
    generate-ddl: true
    properties:
      hibernate.format_sql: true
      hibernate.auto_quote_keyword: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
